In [2]:
#Importing Libraries
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

#Loading Dataset
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

#Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [3]:
df_salary = df[pd.notna(df['salary_year_avg'])]

In [4]:
df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

In [5]:
def projected_salary(salary):
    return salary * 1.03
df_salary['df_salary_inflated'] = df_salary['salary_year_avg'].apply(projected_salary)
df_salary[['salary_year_avg', 'df_salary_inflated']]

#df_salary['df_salary_inflated'] = df_salary['salary_year_avg'].apply(lambda x: x * 1.03)

        salary_year_avg  df_salary_inflated
28             109500.0           112785.00
77             140000.0           144200.00
92             120000.0           123600.00
100            228222.0           235068.66
109             89000.0            91670.00
...                 ...                 ...
785624         139216.0           143392.48
785641         150000.0           154500.00
785648         221875.0           228531.25
785682         157500.0           162225.00
785692         157500.0           162225.00

[22003 rows x 2 columns]

In [9]:
import ast

In [6]:
df_skills = df[pd.notna(df['job_skills'])]

In [7]:
df_skills["job_skills"].apply(type).value_counts()

job_skills
<class 'str'>    668704
Name: count, dtype: int64

In [10]:
df_skills["job_skills"] = df_skills["job_skills"].apply(ast.literal_eval)

In [11]:
type(df_skills['job_skills'].iloc[0])

list

In [ ]:
# import ast
# df['job_skills'] = df['job_skills'].apply(lambda skill_list: ast.literal_eval(skill_list) if pd.notna(skill_list) else skill_list)

In [21]:
#Check if 'Senior' is present in the job title
def projected_salary(row):
    if 'Senior' in row['job_title_short']:
        return row['salary_year_avg'] * 1.05
    else:
        return row['salary_year_avg'] * 1.03

df_salary['salary_year_inflated'] = df_salary.apply(projected_salary, axis=1)

df_salary[['job_title_short', 'salary_year_avg', 'salary_year_inflated']].groupby('job_title_short').mean().sort_values(by='salary_year_inflated', ascending=False).head(10)

                           salary_year_avg  salary_year_inflated
job_title_short
Senior Data Scientist        154206.292996         161916.607646
Senior Data Engineer         145840.611624         153132.642205
Data Scientist               135988.837171         140068.502286
Data Engineer                130125.604250         134029.372377
Machine Learning Engineer    126774.315972         130577.545451
Senior Data Analyst          113911.363665         119606.931848
Software Engineer            113393.760054         116795.572856
Cloud Engineer               111268.453846         114606.507462
Data Analyst                  93841.907854          96657.165090
Business Analyst              91082.612833          93815.091218